package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;	
	
import dao.mappers.IMapResultSetIntoEntity;	
import dao.repositories.ICustomerRepository;
import dao.uow.IUnitOfWork;
import Lalunaa.HamsterGym.Customer;
	

	public class CustomerRepository extends RepositoryBase<Customer> 
	implements ICustomerRepository {
		
		private PreparedStatement getName;
		private PreparedStatement getSurname;
		
	    

		public CustomerRepository(Connection connection, 
			IMapResultSetIntoEntity<Customer> mapper, IUnitOfWork uow) {
			super(connection,mapper, uow);
		
		
		try{
			 getName = connection.prepareStatement(getNameSql());
			 getSurname = connection.prepareStatement(getSurnameSql()); 
			 }catch(SQLException e){
		    e.printStackTrace();
        }		
		}	
		
		
		protected String getNameSql(){return "SELECT * FROM customer where name = ?";}
		protected String getSurnameSql(){return "SELECT * FROM customer where surname=?";}
		
		
			@Override
			protected String createTableSql() {
				return "" + "CREATE TABLE customer("
						+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
						+ "name varchar(20)," + "surname varchar(50)" + ")";
			}

			@Override
			protected String tableName() {
				return "customer";
			}
			
			protected String insertSql() {
				return "INSERT INTO customer(name, surname) VALUES (?,?)";
			}
			
			protected String updateSql() {
				return "UPDATE customer SET (name, surname)=(?,?) WHERE id=?";
			}
			
			protected String deleteSql(int id) {				
				return "DELETE FROM customer WHERE id=?";
			}
			
			protected String selectAllSql() {
				return "SELECT * FROM customer";
			}
			
			@Override
			protected void setUpdate(Customer entity) throws SQLException {
				
				update.setString(1, entity.getName());
				update.setString(2, entity.getSurname());	
				
			}

			@Override
			protected void setInsert(Customer entity) throws SQLException {
				
				insert.setString(1, entity.getName());
				insert.setString(2, entity.getSurname());		
					
			}

			private List<Customer> searchBy(String value){
		        List<Customer> customers = new ArrayList<Customer>();
		        try{
		            getName.setString(1,value);
		            ResultSet resultSet = getName.executeQuery();
		            while(resultSet.next()){
		                customers.add(mapper.map(resultSet));
		            }
		        }catch (SQLException e){
		            e.printStackTrace();
		        }
		        return customers;
		    }


			 public List<Customer> withName(String name) {
			        return searchBy(name);
			    }


			    public List<Customer> withSurname(String surname) {
			        return searchBy(surname);
			    }
			    
			   

				public List<Customer> withActivities(Object activities) {
					return searchBy((String)activities);
				}
				
			}	
		

