package Lalunaa.HamsterGym;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class CustomerRepository extends RepositoryBase {
	
		
	String insertSql = "INSERT INTO customer(name, surname) VALUES (?,?)";
	String selectByIdSql = "SELECT * FROM customer WHERE id=?";
	
	PreparedStatement insert;
	PreparedStatement selectById;
	
	public CustomerRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Customer get(int customerId){
		try{
			selectById.setInt(1, customerId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				Customer result = new Customer();
				result.setId(rs.getInt("id"));
				result.setName(rs.getString("name"));
				result.setSurname(rs.getString("surname"));
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
		
	}
	
	public void add(Customer customer) {
		try {
			insert.setString(1, customer.getName());
			insert.setString(2, customer.getSurname());
			insert.executeUpdate();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE customer("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "customer";
	}


}
